name: Run Tests, Lint, and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]  # если dev-зависимости указаны в pyproject.toml или setup.cfg
        pip install pytest pytest-cov flake8 build

    - name: Run flake8 linter
      run: |
        flake8 duplicate_finder tests

    - name: Run tests with coverage
      run: |
        pytest --cov=duplicate_finder --cov-report=term --cov-report=html

    - name: Upload coverage to GitHub (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml

    - name: Build distribution package
      run: |
        python -m build
