name: Release Package

on:
  push:
    tags:
      - 'v*.*.*'  # Example: v1.0.0

jobs:
  build-and-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needs for trusted publishing

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build backend
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
